print("Enter the principle amount")
a = float(input())
print("Enter the interest rate")
b = float(input())
print("Enter the number of times interest applied per time period")
c = int(input())
print("Enter the number of years")
d = float(input())
e = a * ((1 +(b/(c*100)))**(d*c))
print("The total amount to pay : " + str(e))
